resume: True
weight: ./checkpoints/instPIFu_pix3d/model_best_pix3d.pth #use network weight trained on pix3d
finetune: False
method: instPIFu
exp_name: instPIFu_result
phase: reconstruction
debug: False
device:
  use_gpu: True
  gpu_ids: '2'
data:
  dataset: sunrgbd_recon
  split: ./data/sunrgbd/splits/test_object.json
  image_height: 200
  image_width: 268
  batch_size: 1
  num_workers: 1
  use_aug: False
  use_positional_embedding: True
  marching_cube_resolution: 256
  multires: 4
  use_crop: True
  use_instance_mask: True
  use_pred_pose: True
  pred_pose_path: ./checkpoints/3d_box_test_new/visualization
model:
  mlp_dim: [549, 1024, 512, 256, 128, 1]
  no_residual: False
  num_stack: 4
  norm: group
  hg_down: ave_pool
  num_hourglass: 2
  hourglass_dim: 256
  skip_hourglass: False
  multires: 4
  use_atten: True
  global_recon: True
  global_mlp_dim: [293,512,256,128,1]
other:
  model_save_dir: ./checkpoints
  dump_result: True
  dump_interval: 1000
  scale_back: False


